#!/bin/sh
. ./apikey.sh

mkdir -p pages
cd pages

for KEYWORDS in \
	"big+data" \
	"realite+augmentee" \
	"3d"
do
	curl -o data.json "https://www.googleapis.com/youtube/v3/search?type=video&q=${KEYWORDS}&maxResults=11&part=snippet&key=${APIKEY}"
	FILENAME=$(echo ${KEYWORDS} | sed 's/+/_/')
	cat ../header.html | tee ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '<body>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '<nav>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '	<a href="big_data_video.html">Big Data</a>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '	<a href="realite_augmentee_video.html">Réalité Augmentée</a>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '	<a href="3d_video.html">3D</a>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '</nav>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '<nav>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo "	<a href=\"${FILENAME}_video.html\">Vidéo</a>" | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo "	<a href=\"${FILENAME}_author.html\">Auteur</a>" | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '</nav>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '<ul>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	/usr/bin/env python3 ../get_links.py >> ${FILENAME}_video.html
	echo '</ul>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '</body>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	echo '</html>' | tee -a ${FILENAME}_video.html ${FILENAME}_author.html >/dev/null
	rm data.json
done
cd ../
