# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('channelId', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('channelTitle', models.CharField(default='', max_length=255)),
                ('nbVideos', models.CharField(default='', max_length=255)),
                ('createdDate', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoId', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('created_date', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('thumbnail', models.CharField(default='', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youminer.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youminer.Category')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youminer.Category'),
        ),
    ]
