# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youminer', '0002_auto_20171205_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
