# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youminer', '0002_auto_20171128_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
