# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youminer', '0003_auto_20171205_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
