# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youminer', '0003_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
