# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youminer', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nbQuizz',
            field=models.IntegerField(default=0),
        ),
    ]
