# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youminer', '0008_auto_20180204_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
